META_DSC_MAX_LEN = 150
META_DSC_MIN_LEN = 120
META_DSC_COUNT = 1

META_KEYWORD_MAX_LEN = 150
META_KEYWORD_MIN_LEN = 120
META_KEYWORD_COUNT = 1

SITE_TITLE_MAX_LEN = 60
SITE_TITLE_MIN_LEN = 20
SITE_TITLE_COUNT = 1

H1_MAX_LEN = 70
H1_MIN_LEN = 20
H1_COUNT = 1

H2_MAX_LEN = 70
H2_MIN_LEN = 20
H2_COUNT = 25

FROM_TITLE = 'TEAM @RBS'
MAIL_SUBJECT = 'Having Trouble With Your SEO?'

SMTP_HOST = 'smtp.gmail.com'
SMTP_USERNAME = 'ethanedevloper@gmail.com'
SMTP_PASS = 'ethanedevloper@123#'
SMTP_PORT = 587
